hash-format = "sha256"

[[files]]
file = "config/superbwarfare-client.toml"
hash = "cfcb071fe06862d9e1ffd7c9ac70aa0f70aab073657e8d61aae535a7472ae8d6"

[[files]]
file = "config/tacztweaks.json"
hash = "ec4540a020a34b1b1fca27dcee0d5c1026d97a7acb1187a889950788f6bec39a"

[[files]]
file = "mods/MCSP-1.20.1-V1.0.5.jar"
hash = "94242f0fbd5f7fe62293d4e5d91148aaf5ec0d34656fe5c91b5b2a3baea06ce9"

[[files]]
file = "mods/ashvehicle-4.1-8.7-SNAPSHOT.jar"
hash = "79d55640685b5abfa5f510355b97edc5bc1203464167ae8c8384a03d99dd9924"

[[files]]
file = "mods/better-parachute-paraquedas.pw.toml"
hash = "20a1b075e968ab360874cd9f08209bf4e4a3bbb2f0b3d8493538032b65313695"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "c1bdeff356cd2ac164e2c0e6d0ceeda234db9774c2df44fb9f0e71d3960cc3f1"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/endlessammo-1.2.0.jar"
hash = "aad1f64a7469f11c6fa68e2f6f9d977f0c3e3ca5a45be50bbffcd89506f16ab3"

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/fels-machine-guns-wwii.pw.toml"
hash = "ccd8a93a81f32b7e1a347c899504c27b9a34bc2313a40e95b9b97d12de3c258d"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "376f8a190f00bd120193d7a665ebe1b03dfe329cc395f7d944f7216c1182c84d"
metafile = true

[[files]]
file = "mods/geckolib-forge-1.20.1-4.7.2.jar"
hash = "13926e4c3f64dcf67109ed3e3c85d6eb9ba8089eaa308de17eb15d2f846e3f3d"

[[files]]
file = "mods/iguana-lib.pw.toml"
hash = "0834edba8208be0c39e6681efb671db7a8504c2f8086189a062bf303001b7ee8"
metafile = true

[[files]]
file = "mods/immersive_aircraft-1.2.2+1.20.1-forge.jar"
hash = "84e1e87d32e4a8b36cd9529efcb633c2a8c8c189d15e61a7b422310047566b89"

[[files]]
file = "mods/jei-1.20.1-forge-15.20.0.112.jar"
hash = "2d3a86f503dbde51afa5142951525c37e227016ce8d9e7dfd10bbdd9233f0204"

[[files]]
file = "mods/kotlinforforge-4.11.0-all.jar"
hash = "ef988f86d170af499d147ea8a5c34c99dbd6d8f4a5ad236a4b43818dc4470a10"

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "48b6be3ef711114f233e0c36d7f625b1e42c247c3e78a51fd7498886657a2384"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "33af5f73cc7b802cf45b02ef7ec7b9a516919d55ed32a035a4661f33331b5531"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "6445161fb93a765e776f97573a32af44d0615133b76f33d56da1b842eb5fc377"
metafile = true

[[files]]
file = "mods/manyideas-core.pw.toml"
hash = "138932c84890c25da9e9a2ae1d8b450b627d6c13e2cd048e60fd4cfec7cd76ea"
metafile = true

[[files]]
file = "mods/manyideas-doors.pw.toml"
hash = "548d16d7f0c909854128a1eca9eca35b4837e8c04901370773cd5e24a57017e8"
metafile = true

[[files]]
file = "mods/mcw-fences-1.2.0-1.20.1forge.jar"
hash = "6fe3bc1e2bb26854e2f0f62bacbaea518b4681b342fca52d2ce6c595775c4c88"

[[files]]
file = "mods/mcw-furniture-3.3.0-mc1.20.1forge.jar"
hash = "65562bcfcf1deb473e68f9f06605f43a521670e2ce3712a60b91bbd2e479fe7c"

[[files]]
file = "mods/mcw-lights-1.1.2-mc1.20.1forge.jar"
hash = "c729c555e5635aeea17ab90acf1532488f96ed409b937ac1a71b40b61d46c1b1"

[[files]]
file = "mods/mcw-mcwholidays-1.1.1-mc1.20.1forge.jar"
hash = "bdfc2db24c71c40b19c136666a12460556f9f39e49bb2092d6881b67f42896de"

[[files]]
file = "mods/mcw-mcwwindows-2.4.1-mc1.20.1forge.jar"
hash = "438344fb202a594f47bf490a638a80bf70f4a74c0f1afcec7aa896a753235710"

[[files]]
file = "mods/mcw-stairs-1.0.1-1.20.1forge.jar"
hash = "2e79425f5dfe585947270063f71e4fc14ef59f1bcd6911a489e879121e1e0b94"

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/paladins-furniture.pw.toml"
hash = "a1c2e02ee5cba7a3fc13315d35b04919fdb8cfdb453f023372d4e1b369607f1b"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "55c6d0b8ee25fd6a37a964805de3d2eab3f20d73a88ba77a63b4a51fd985d9dd"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "b52622122c19a3894e62fc5506d7c3332d202504fd406d6718be646f979feb40"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4ab869d8784f4ac318b5c92fa3d9e65f997352b8b57f34b409ca6f171637f0fe"
metafile = true

[[files]]
file = "mods/recipes-library.pw.toml"
hash = "652abe9780694aacade5cd54711cd25228f7e2f7656e98207a14ce5c639270c7"
metafile = true

[[files]]
file = "mods/refurbished_furniture-forge-1.20.1-1.0.14.jar"
hash = "a44d4b232e906ecdbbddafec5b9edc2c9a1dc8a8fa7d7ea0782f0a694eb9d21a"

[[files]]
file = "mods/superbwarfare-1.20.1-0.8.7-final-d6ea9a72b.jar"
hash = "d2ace9eaf40d0424dc8909bfd327bbec97a9a1329e0eeb2fb8aa4090094298c8"

[[files]]
file = "mods/tacz-1.20.1-1.1.6-hotfix.jar"
hash = "f9b4bb27cecff72750e6ef6e72a1ae579006f7dd1d5ac213c9b228fb4c8747fb"

[[files]]
file = "mods/tacz-gucci-vuitton-attachments.pw.toml"
hash = "a15342a63bf18e434f474e8a420af783aceb24b70ca261d0513857668b8eca84"
metafile = true

[[files]]
file = "mods/tacz-lesraisins-tactical-equipements.pw.toml"
hash = "d97655330510c21898fe03027bd9841e34af2c6bc89372f22a6b23e71068b5ab"
metafile = true

[[files]]
file = "mods/tacz-tweaks.pw.toml"
hash = "d37cfe952a966bc4ffde79eb53b730de9b7d77fc515c30650133d13d9cc99001"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3b3d035b89519faccc4ddd8b0b4407ce96c0eb49068fe50a445d43a3baa8bea"
metafile = true

[[files]]
file = "options.txt"
hash = "1a76e3ab121ed7defef02f1a5d53d9100224938d5f950279175b5463042d5886"

[[files]]
file = "tacz/ARIPS_ver.1.2.3-LVS.zip"
hash = "649d2c2bbfa726e0c42d6f4f9a7c9a6285e0b17e617f022f0925804cd86a5efd"

[[files]]
file = "tacz/Apocalypse_v1.1.7_G.zip"
hash = "d5b620657cf0afe89ee671d3d89e7698341106c3b5ac184a8b8688463e2783f2"

[[files]]
file = "tacz/Eurrussia-Variantz-3.0.5c-hotfix.zip"
hash = "9b4fd2f14db92ab2cd99e78b44ffb380badfce62090211813efefba81226ba00"

[[files]]
file = "tacz/GunpowderRevolution_gunpack v1.2.7.zip"
hash = "5d1deb681fb087442b35f16100aacdf81a13cb9dfd5a1085fef7169e3088a749"

[[files]]
file = "tacz/RFP v1.0.8.zip"
hash = "359c83622da3baf6f15daddc98e96778ca91d6a7cf099aa82e40cd448e061196"

[[files]]
file = "tacz/Rebel v1.0.8a.zip"
hash = "a6b62ce960763b9fb006524f5fee7cc463b7828fd348414830bcf03187ef5fd9"

[[files]]
file = "tacz/Suffuse-GunSmoke-Pack1.0.7--hotfix.zip"
hash = "db829e453f38ec5e91731b90ea48ea13b062e5bd936a12b27407cefba752e439"

[[files]]
file = "tacz/The Continental v1.4.zip"
hash = "73b8db95c171e01131aeba7e77739612721425f8a93ca000b3914500d05a312c"

[[files]]
file = "tacz/Trench_Tactics v0.05.zip"
hash = "3d3efcd3e4252768d3bf16a17c3975e654d134b05103fd90ad55a0f0c2276b3e"

[[files]]
file = "tacz/[TACZ1.1.4]ClassicRCCRP v1.1.0 release hf.zip"
hash = "26728d80db900cc369800a317b095d571d101a18f1ca27c9e10bb91197a4b4db"

[[files]]
file = "tacz/antiques_gunpack_v0.2.2.zip"
hash = "f63d1a9526acb0f051c43aba3583b27e67c9011a61152dadc102a25467649035"

[[files]]
file = "tacz/tacz-pre.toml"
hash = "380a3105e0739f6bbae202352d29d68a7a1e88bab8912c95cd9204492c7d48ae"

[[files]]
file = "tacz/throwable_thing_v1.3.1-1.1.4_hotfix_1.zip"
hash = "af32e24ff6f7c4249d078259cb871f853226493b63992063c140d73a2bbc2711"
