name = "Custom Modpack"
author = "tekitou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44a6238a8d45bae2658302adc789c3707d1992fb0e6cc84c08cd406e1dcafda5"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
