name = "Custom Modpack"
author = "tekitou"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4c10360061ab47a12815d859afee478354588244d1c47ee22449ab236033fdd"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
