name = "Custom Modpack"
author = "tekitou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c16d24cf24f0a2697528b1a20926938a8da5f61a5d3ae495c3ab09f38fc3ae5e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
