name = "Custom Modpack"
author = "tekitou"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "122dd9934e7731cf51c101086b7bf13b111f8efef086a0fed3939a3f3efec3ee"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
