name = "Custom Modpack"
author = "tekitou"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87598c6366f9b6a33c6f0013106fc7799c57d2a4f3a5d2000be8f5695f433390"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
