name = "Custom Modpack"
author = "tekitou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "056edb05c26c2eddd699776345122ae1573c2bc2b9a50c0a814f1c66633a0339"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
