name = "Custom Modpack"
author = "tekitou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8aac56a595d487dedd9c1be2614672cac48bc43d8ead55a09828b0c56c3ca174"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
