name = "Custom Modpack"
author = "tekitou"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b051dd09b2ffe09da6b30a2468cc639b256b627e9fa022b4f7fd59aeab60c8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
